# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

language: python
sudo: false
cache:
  # See http://docs.travis-ci.com/user/caching/#pip-cache
  directories:
    - $HOME/.cache/pip
addons:
  apt:
    packages:
    - libfreeimage3
    - texlive 
    - texlive-latex-extra 
    - dvipng
    - python-qt4

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1fea29525e8b929dd7c7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

before_install:
    - pip install -U pip
    - source tools/travis_before_install.sh

    - which python; python --version
    - python check_bento_build.py
    - tools/build_versions.py

install:
    - python setup.py develop

script: tools/travis_script.sh

after_success:
    - coveralls
