# vim ft=yaml
# travis-ci.org definition for skimage build

language: python
python:
    - "2.7"
    - "3.2"
virtualenv:
    system_site_packages: true
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then export PYTHON=python; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then export PYTHON=python3; fi
    - sudo apt-get update
    - sudo apt-get install $PYTHON-dev
    - sudo apt-get install $PYTHON-numpy
    - sudo apt-get install $PYTHON-scipy
    - sudo apt-get install $PYTHON-pip
    - sudo apt-get install libfreeimage3
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then sudo apt-get install $PYTHON-qt4; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then sudo apt-get install $PYTHON-pyqt4; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then sudo apt-get install $PYTHON-matplotlib; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then sudo pip install git+git://github.com/matplotlib/matplotlib.git@v1.2.x; fi
    - sudo pip install cython
    - sudo pip install flake8
    - sudo pip install six
install:
    - python setup.py build_ext --inplace
script:
    # Check if setup.py's match bento.info
    - $PYTHON check_bento_build.py
    # Setup matplotlib settings
    - mkdir $HOME/.matplotlib
    - "echo 'backend : Agg' > $HOME/.matplotlib/matplotlibrc"
    - "echo 'backend.qt4 : PyQt4' >> $HOME/.matplotlib/matplotlibrc"
    # Run all tests
    - nosetests --exe -v --with-doctest --ignore-files='^\.' --ignore-files='^setup\.py$$' --ignore-files='^_test' skimage
    # Run all doc examples
    - export PYTHONPATH=$(pwd):$PYTHONPATH
    - for f in doc/examples/*.py; do $PYTHON "$f"; if [ $? -ne 0 ]; then exit 1; fi done
    - for f in doc/examples/applications/*.py; do $PYTHON "$f"; if [ $? -ne 0 ]; then exit 1; fi done
    # Run pep8 and flake tests
    - flake8 --exit-zero --exclude=test_*,six.py skimage doc/examples viewer_examples
