# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

language: python

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1fea29525e8b929dd7c7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4

before_install:
    - export DISPLAY=:99.0
    - export PYTHONWARNINGS="all"
    - export WHEELHOUSE="--no-index --find-links=http://travis-wheels.scikit-image.org/"
    - sudo apt-get update

    - travis_retry tools/travis_setup.sh

    - source ~/venv/bin/activate
    - which python
    - python --version
    - python check_bento_build.py

    - tools/header.py "Dependency versions"
    - tools/build_versions.py


install:
    - python setup.py build_ext --inplace
    - python setup.py install

script:
    - tools/header.py "Run all tests with minimum dependencies"
    - nosetests --exe -v skimage

    - tools/header.py "Pep8 and Flake tests"
    - flake8 --exit-zero --exclude=test_*,six.py skimage doc/examples viewer_examples

    - travis_retry tools/travis_install_optional.sh
    - tools/travis_test.sh

after_success:
    - coveralls
