# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

language: python

env: TEST_ARGS=""

matrix:
  include:
    - python: "2.6"
    - python: "2.7_with_system_site_packages"
    - python: "3.2"
    - python: "3.3"
      env: TEST_ARGS="--with-cov --cover-package"
    - python: "3.4"

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sudo apt-get update

    - export WHEELHOUSE="--no-index --find-links=http://wheels.scikit-image.org/"

    - travis_retry sh tools/travis_setup.sh

install:
    - tools/header.py "Dependency versions"
    - tools/build_versions.py
    - export PYTHONWARNINGS=all
    - python setup.py build_ext --inplace

script:
    - tools/header.py "Run all tests with minimum dependencies"
    - nosetests --exe -v skimage

    - tools/header.py "Pep8 and Flake tests"
    - flake8 --exit-zero --exclude=test_*,six.py skimage doc/examples viewer_examples

    - travis_retry sh tools/travis_get_optional.sh

    - tools/header.py "Run doc examples"
    - export PYTHONPATH=$(pwd):$PYTHONPATH
    - for f in doc/examples/*.py; do python "$f"; if [ $? -ne 0 ]; then exit 1; fi done
    - for f in doc/examples/applications/*.py; do python "$f"; if [ $? -ne 0 ]; then exit 1; fi done

    - tools/header.py "Run tests with all dependencies"
    # run tests again with optional dependencies to get more coverage
    - nosetests --exe -v --with-doctest $TEST_ARGS

after_success:
    - coveralls
