# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

language: python

python:
- 2.6
- "2.7_with_system_site_packages"
- 3.2
- 3.3
- 3.4

before_install:
    - tools/travis_setup.sh

install:
    - python setup.py build_ext --inplace
    - python setup.py install

script:
    - tools/travis_test.sh

after_success:
    - coveralls
