# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

language: python

env:
    WHEELHOUSE="--no-index --find-links=http://wheels.scikit-image.org/"
    PYTHONWARNINGS="all"
    DISPLAY=:99.0

python:
- 2.6
- "2.7_with_system_site_packages"
- 3.2
- 3.3
- 3.4

before_install:
    - sh -e /etc/init.d/xvfb start
    - sudo apt-get update
    - tools/travis_setup.sh

install:
    - python setup.py build_ext --inplace

script:
    - tools/travis_test.sh

after_success:
    - coveralls
